
services:
  # Сервис Dispatcher
  servertgbot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: servertgbot
    restart: unless-stopped
    ports:
      - 9000:9000

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_URL: ${BOT_URL}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./.env:/servertgbot/.env  # Копируем .env в /app


